### ISSUE TITLE
does i need open that program when open genshin? or only first time?

### ISSUE THREAD

**Issue by luanon404** [Ev3nt/EasyPeasy-Bypass#1]

**Comment by Ev3nt** [comment]
You should run this after starting the game, but now I don't know if my anti-cheat bypass will work.

**Comment by luanon404** [comment]
i can open cheat engine, can you make for honkai star rail? i cant use this to bypass hsr

**Comment by Ev3nt** [comment]
Sheesh, they really didn't fix it. xDDD

**Comment by Ev3nt** [comment]
> i can open cheat engine, can you make for honkai star rail? i cant use this to bypass hsr

I'm sorry, but I don't like this game, which is why I'm not going to do anything for it.

**Comment by luanon404** [comment]
oh, thanks
